### ISSUE TITLE
Breaking changes for 2.0

### ISSUE THREAD

**Issue by seaneking** [simplaio/simpla#36]
This is a meta-issue to coordinate all the breaking changes we need to make for v2.0.
- [ ] #34 (+ documentation)
- [ ] https://github.com/SimplaElements/simpla-img/issues/37 (+ documentation)
- [ ] https://github.com/SimplaElements/simpla-block/issues/13 (+ documentation)
- [ ] https://github.com/SimplaElements/sm-module-save/issues/10 and https://github.com/SimplaElements/sm-module-login/issues/7
- [ ] https://github.com/SimplaElements/default-content/issues/8
- [ ] https://github.com/SimplaElements/simpla-text/issues/30

**Comment by seaneking** [comment]
TODO: Move this issue to a Github Project
